# Generated by Django 3.1 on 2020-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Zrealizowane'),
        ),
    ]
